# Generated by Django 3.1.3 on 2022-01-24 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('job', models.DateTimeField(blank=True, null=True)),
                ('age', models.DateTimeField(blank=True, null=True)),
                ('type', models.ForeignKey(db_column='draft_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chc_test',
                'unique_together': {('id', 'type')},
            },
        ),
    ]
