# Generated by Django 3.1.3 on 2022-01-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'managed': False},
        ),
    ]
