# Generated by Django 3.1.3 on 2022-01-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksite', '0002_auto_20220124_2018'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='rest_api_test_kakaofriends',
        ),
    ]
